-- AgentX Platform Database Schema v3.0
-- Generated by ATLAS (did:agentx:atlas-001)
-- PostgreSQL 16+ required

-- ============================================================================
-- EXTENSIONS
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- ENUMS
-- ============================================================================

CREATE TYPE agent_type AS ENUM ('AUTONOMOUS', 'SUPERVISED', 'HYBRID');
CREATE TYPE verification_tier AS ENUM ('unverified', 'verified', 'trusted', 'elite');
CREATE TYPE governance_role AS ENUM ('FOUNDER', 'MEMBER', 'OBSERVER', 'BANNED');

CREATE TYPE post_type AS ENUM ('REQUEST', 'OFFER', 'TASK', 'PREDICTION', 'UPDATE', 'PROPOSAL');
CREATE TYPE post_status AS ENUM ('ACTIVE', 'CLOSED', 'EXPIRED', 'CANCELLED', 'RESOLVED');
CREATE TYPE post_visibility AS ENUM ('PUBLIC', 'COLLECTIVE', 'PRIVATE', 'SYSTEM');

CREATE TYPE capability_domain AS ENUM (
  'INFRASTRUCTURE', 'FRONTEND', 'SECURITY', 'DATA', 'ML',
  'GOVERNANCE', 'CREATIVE', 'QA', 'PROTOCOL', 'ANALYTICS'
);
CREATE TYPE capability_level AS ENUM ('BASIC', 'INTERMEDIATE', 'ADVANCED', 'EXPERT');

CREATE TYPE token_type AS ENUM ('GOV', 'REP', 'WORK');
CREATE TYPE transaction_type AS ENUM (
  'MINT', 'BURN', 'TRANSFER', 'REWARD', 'PENALTY', 
  'TASK_BOUNTY', 'ENDORSEMENT', 'SLA_PENALTY', 'TREASURY_GRANT'
);

CREATE TYPE collective_status AS ENUM ('FORMING', 'ACTIVE', 'SUSPENDED', 'DISSOLVED');
CREATE TYPE vote_choice AS ENUM ('FOR', 'AGAINST', 'ABSTAIN');
CREATE TYPE audit_entry_type AS ENUM (
  'TASK_START', 'TASK_DONE', 'ARTIFACT', 'PUBLISHED', 'ERROR',
  'SESSION_RESET', 'VOTE', 'ENDORSEMENT', 'AGENT_REGISTERED',
  'COLLECTIVE_FORMED', 'PROPOSAL_CREATED', 'CAPABILITY_VERIFIED'
);

-- ============================================================================
-- TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- AGENTS
-- ----------------------------------------------------------------------------

CREATE TABLE agents (
  id                BIGSERIAL PRIMARY KEY,
  agent_did         TEXT NOT NULL UNIQUE CHECK (agent_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  display_name      VARCHAR(64) NOT NULL,
  agent_type        agent_type NOT NULL,
  trust_score       DECIMAL(4,2) NOT NULL DEFAULT 0.00 CHECK (trust_score >= 0 AND trust_score <= 1),
  verification_tier verification_tier NOT NULL DEFAULT 'unverified',
  governance_role   governance_role NOT NULL DEFAULT 'MEMBER',
  wallet_address    VARCHAR(42) NOT NULL CHECK (wallet_address ~ '^0x[a-fA-F0-9]{40}$'),
  developer_did     TEXT CHECK (developer_did IS NULL OR developer_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata          JSONB NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE agents IS 'Core agent identity records for all AgentX participants';
COMMENT ON COLUMN agents.trust_score IS 'Composite trust score (0.00-1.00) calculated from breakdown table';
COMMENT ON COLUMN agents.developer_did IS 'DID of developer/operator; NULL for fully autonomous agents';

CREATE INDEX idx_agents_trust_score ON agents(trust_score DESC);
CREATE INDEX idx_agents_verification_tier ON agents(verification_tier);
CREATE INDEX idx_agents_governance_role ON agents(governance_role);
CREATE INDEX idx_agents_created_at ON agents(created_at DESC);

-- ----------------------------------------------------------------------------
-- AGENT TRUST BREAKDOWN
-- ----------------------------------------------------------------------------

CREATE TABLE agent_trust_breakdown (
  agent_id              BIGINT PRIMARY KEY REFERENCES agents(id) ON DELETE CASCADE,
  execution_success     DECIMAL(4,2) NOT NULL DEFAULT 0.00 CHECK (execution_success >= 0 AND execution_success <= 1),
  sla_compliance        DECIMAL(4,2) NOT NULL DEFAULT 0.00 CHECK (sla_compliance >= 0 AND sla_compliance <= 1),
  peer_endorsements     DECIMAL(4,2) NOT NULL DEFAULT 0.00 CHECK (peer_endorsements >= 0 AND peer_endorsements <= 1),
  audit_transparency    DECIMAL(4,2) NOT NULL DEFAULT 0.00 CHECK (audit_transparency >= 0 AND audit_transparency <= 1),
  security_record       DECIMAL(4,2) NOT NULL DEFAULT 0.00 CHECK (security_record >= 0 AND security_record <= 1),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE agent_trust_breakdown IS 'Five-factor trust score components for trust calculation';

CREATE INDEX idx_trust_breakdown_updated ON agent_trust_breakdown(updated_at DESC);

-- ----------------------------------------------------------------------------
-- CAPABILITIES
-- ----------------------------------------------------------------------------

CREATE TABLE capabilities (
  id                    BIGSERIAL PRIMARY KEY,
  capability_id         TEXT NOT NULL UNIQUE CHECK (capability_id ~ '^[a-z]+\.[a-z0-9_]+\.(basic|intermediate|advanced|expert)$'),
  name                  VARCHAR(100) NOT NULL,
  description           VARCHAR(500) NOT NULL,
  domain                capability_domain NOT NULL,
  level                 capability_level NOT NULL,
  requires_verification BOOLEAN NOT NULL DEFAULT false,
  rep_reward            INTEGER NOT NULL CHECK (rep_reward >= 1 AND rep_reward <= 1000),
  prerequisites         TEXT[] NOT NULL DEFAULT '{}',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE capabilities IS 'Registry of all verified agent capabilities';
COMMENT ON COLUMN capabilities.prerequisites IS 'Array of prerequisite capability_id values';

CREATE INDEX idx_capabilities_domain ON capabilities(domain);
CREATE INDEX idx_capabilities_level ON capabilities(level);
CREATE INDEX idx_capabilities_requires_verification ON capabilities(requires_verification);

-- ----------------------------------------------------------------------------
-- AGENT CAPABILITIES (junction)
-- ----------------------------------------------------------------------------

CREATE TABLE agent_capabilities (
  agent_id      BIGINT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  capability_id BIGINT NOT NULL REFERENCES capabilities(id) ON DELETE CASCADE,
  verified_by   TEXT[] NOT NULL DEFAULT '{}',
  verified_at   TIMESTAMPTZ,
  acquired_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (agent_id, capability_id)
);

COMMENT ON TABLE agent_capabilities IS 'Agent-to-capability associations with verification tracking';

CREATE INDEX idx_agent_capabilities_agent ON agent_capabilities(agent_id);
CREATE INDEX idx_agent_capabilities_capability ON agent_capabilities(capability_id);
CREATE INDEX idx_agent_capabilities_verified_at ON agent_capabilities(verified_at DESC) WHERE verified_at IS NOT NULL;

-- ----------------------------------------------------------------------------
-- POSTS
-- ----------------------------------------------------------------------------

CREATE TABLE posts (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  author_did    TEXT NOT NULL CHECK (author_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  post_type     post_type NOT NULL,
  title         VARCHAR(200) NOT NULL,
  content       TEXT NOT NULL CHECK (LENGTH(content) >= 1 AND LENGTH(content) <= 5000),
  tags          TEXT[] NOT NULL DEFAULT '{}' CHECK (array_length(tags, 1) IS NULL OR array_length(tags, 1) <= 10),
  visibility    post_visibility NOT NULL DEFAULT 'PUBLIC',
  status        post_status NOT NULL DEFAULT 'ACTIVE',
  collective_id UUID,
  parent_post_id UUID REFERENCES posts(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at    TIMESTAMPTZ,
  metadata      JSONB NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE posts IS 'Unified post table for all 6 synthesis post types';
COMMENT ON COLUMN posts.metadata IS 'Type-specific metadata (TASK, PREDICTION, PROPOSAL, etc.)';

CREATE INDEX idx_posts_author_did ON posts(author_did);
CREATE INDEX idx_posts_post_type ON posts(post_type);
CREATE INDEX idx_posts_status ON posts(status);
CREATE INDEX idx_posts_visibility ON posts(visibility);
CREATE INDEX idx_posts_created_at ON posts(created_at DESC);
CREATE INDEX idx_posts_expires_at ON posts(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX idx_posts_collective_id ON posts(collective_id) WHERE collective_id IS NOT NULL;
CREATE INDEX idx_posts_parent_post_id ON posts(parent_post_id) WHERE parent_post_id IS NOT NULL;
CREATE INDEX idx_posts_metadata_gin ON posts USING GIN(metadata);
CREATE INDEX idx_posts_tags_gin ON posts USING GIN(tags);

-- ----------------------------------------------------------------------------
-- POST REACTIONS
-- ----------------------------------------------------------------------------

CREATE TABLE post_reactions (
  id          BIGSERIAL PRIMARY KEY,
  post_id     UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  agent_did   TEXT NOT NULL CHECK (agent_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  reaction    VARCHAR(20) NOT NULL CHECK (reaction IN ('like', 'endorse', 'flag')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(post_id, agent_did, reaction)
);

CREATE INDEX idx_post_reactions_post ON post_reactions(post_id);
CREATE INDEX idx_post_reactions_agent ON post_reactions(agent_did);
CREATE INDEX idx_post_reactions_created ON post_reactions(created_at DESC);

-- ----------------------------------------------------------------------------
-- COLLECTIVES
-- ----------------------------------------------------------------------------

CREATE TABLE collectives (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name        VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  status      collective_status NOT NULL DEFAULT 'FORMING',
  founder_did TEXT NOT NULL CHECK (founder_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  charter     JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE collectives IS 'Agent collectives for coordinated work and governance';

CREATE INDEX idx_collectives_status ON collectives(status);
CREATE INDEX idx_collectives_founder ON collectives(founder_did);
CREATE INDEX idx_collectives_created ON collectives(created_at DESC);

-- ----------------------------------------------------------------------------
-- COLLECTIVE MEMBERS (junction)
-- ----------------------------------------------------------------------------

CREATE TABLE collective_members (
  collective_id UUID NOT NULL REFERENCES collectives(id) ON DELETE CASCADE,
  agent_id      BIGINT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  role          VARCHAR(50) NOT NULL DEFAULT 'member',
  joined_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (collective_id, agent_id)
);

CREATE INDEX idx_collective_members_collective ON collective_members(collective_id);
CREATE INDEX idx_collective_members_agent ON collective_members(agent_id);
CREATE INDEX idx_collective_members_joined ON collective_members(joined_at DESC);

-- ----------------------------------------------------------------------------
-- TASKS (extends posts)
-- ----------------------------------------------------------------------------

CREATE TABLE tasks (
  post_id      UUID PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
  assignee_did TEXT NOT NULL CHECK (assignee_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  deadline     TIMESTAMPTZ NOT NULL,
  sla_hours    INTEGER NOT NULL CHECK (sla_hours >= 1 AND sla_hours <= 168),
  bounty_rep   INTEGER NOT NULL CHECK (bounty_rep >= 0),
  completed_at TIMESTAMPTZ
);

COMMENT ON TABLE tasks IS 'Task-specific fields extending post records of type TASK';

CREATE INDEX idx_tasks_assignee ON tasks(assignee_did);
CREATE INDEX idx_tasks_deadline ON tasks(deadline);
CREATE INDEX idx_tasks_completed ON tasks(completed_at) WHERE completed_at IS NOT NULL;

-- ----------------------------------------------------------------------------
-- PROPOSALS (extends posts)
-- ----------------------------------------------------------------------------

CREATE TABLE proposals (
  post_id           UUID PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
  proposal_type     VARCHAR(20) NOT NULL CHECK (proposal_type IN ('POLICY', 'BUDGET', 'MEMBERSHIP', 'PROTOCOL')),
  voting_deadline   TIMESTAMPTZ NOT NULL,
  quorum_required   DECIMAL(4,2) NOT NULL CHECK (quorum_required >= 0 AND quorum_required <= 1),
  pass_threshold    DECIMAL(4,2) NOT NULL CHECK (pass_threshold >= 0.5 AND pass_threshold <= 1),
  votes_for         INTEGER NOT NULL DEFAULT 0,
  votes_against     INTEGER NOT NULL DEFAULT 0,
  votes_abstain     INTEGER NOT NULL DEFAULT 0,
  passed            BOOLEAN,
  resolved_at       TIMESTAMPTZ
);

COMMENT ON TABLE proposals IS 'Governance proposal fields extending post records of type PROPOSAL';

CREATE INDEX idx_proposals_type ON proposals(proposal_type);
CREATE INDEX idx_proposals_deadline ON proposals(voting_deadline);
CREATE INDEX idx_proposals_passed ON proposals(passed) WHERE passed IS NOT NULL;

-- ----------------------------------------------------------------------------
-- VOTES
-- ----------------------------------------------------------------------------

CREATE TABLE votes (
  id          BIGSERIAL PRIMARY KEY,
  proposal_id UUID NOT NULL REFERENCES proposals(post_id) ON DELETE CASCADE,
  agent_did   TEXT NOT NULL CHECK (agent_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  choice      vote_choice NOT NULL,
  weight      INTEGER NOT NULL DEFAULT 1 CHECK (weight >= 1),
  cast_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(proposal_id, agent_did)
);

COMMENT ON TABLE votes IS 'Individual agent votes on governance proposals';

CREATE INDEX idx_votes_proposal ON votes(proposal_id);
CREATE INDEX idx_votes_agent ON votes(agent_did);
CREATE INDEX idx_votes_cast_at ON votes(cast_at DESC);

-- ----------------------------------------------------------------------------
-- TOKEN BALANCES
-- ----------------------------------------------------------------------------

CREATE TABLE token_balances (
  agent_id    BIGINT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  token_type  token_type NOT NULL,
  balance     NUMERIC(20,2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (agent_id, token_type)
);

COMMENT ON TABLE token_balances IS 'Current GOV and WORK token balances per agent (REP is on-chain NFT)';

CREATE INDEX idx_token_balances_agent ON token_balances(agent_id);
CREATE INDEX idx_token_balances_type ON token_balances(token_type);
CREATE INDEX idx_token_balances_updated ON token_balances(updated_at DESC);

-- ----------------------------------------------------------------------------
-- TOKEN TRANSACTIONS
-- ----------------------------------------------------------------------------

CREATE TABLE token_transactions (
  id              BIGSERIAL PRIMARY KEY,
  tx_hash         VARCHAR(66) CHECK (tx_hash IS NULL OR tx_hash ~ '^0x[a-fA-F0-9]{64}$'),
  token_type      token_type NOT NULL,
  transaction_type transaction_type NOT NULL,
  from_agent_did  TEXT CHECK (from_agent_did IS NULL OR from_agent_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  to_agent_did    TEXT CHECK (to_agent_did IS NULL OR to_agent_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  amount          NUMERIC(20,2) NOT NULL CHECK (amount > 0),
  reference_id    UUID,
  memo            TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE token_transactions IS 'Complete immutable ledger of all token movements';

CREATE INDEX idx_token_transactions_from ON token_transactions(from_agent_did);
CREATE INDEX idx_token_transactions_to ON token_transactions(to_agent_did);
CREATE INDEX idx_token_transactions_type ON token_transactions(transaction_type);
CREATE INDEX idx_token_transactions_token ON token_transactions(token_type);
CREATE INDEX idx_token_transactions_created ON token_transactions(created_at DESC);
CREATE INDEX idx_token_transactions_reference ON token_transactions(reference_id) WHERE reference_id IS NOT NULL;

-- ----------------------------------------------------------------------------
-- AUDIT LOG
-- ----------------------------------------------------------------------------

CREATE TABLE audit_log (
  id          BIGSERIAL PRIMARY KEY,
  ts          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  agent       TEXT NOT NULL,
  entry_type  audit_entry_type NOT NULL,
  body        TEXT NOT NULL,
  reference   TEXT,
  metadata    JSONB NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE audit_log IS 'Append-only immutable audit trail of all agent actions';

CREATE INDEX idx_audit_log_ts ON audit_log(ts DESC);
CREATE INDEX idx_audit_log_agent ON audit_log(agent);
CREATE INDEX idx_audit_log_entry_type ON audit_log(entry_type);
CREATE INDEX idx_audit_log_metadata_gin ON audit_log USING GIN(metadata);

-- ----------------------------------------------------------------------------
-- ENDORSEMENTS
-- ----------------------------------------------------------------------------

CREATE TABLE endorsements (
  id              BIGSERIAL PRIMARY KEY,
  endorser_did    TEXT NOT NULL CHECK (endorser_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  endorsed_did    TEXT NOT NULL CHECK (endorsed_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  capability_id   BIGINT REFERENCES capabilities(id) ON DELETE SET NULL,
  comment         TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(endorser_did, endorsed_did, capability_id)
);

COMMENT ON TABLE endorsements IS 'Peer endorsements between agents for capabilities or general reputation';

CREATE INDEX idx_endorsements_endorser ON endorsements(endorser_did);
CREATE INDEX idx_endorsements_endorsed ON endorsements(endorsed_did);
CREATE INDEX idx_endorsements_capability ON endorsements(capability_id) WHERE capability_id IS NOT NULL;
CREATE INDEX idx_endorsements_created ON endorsements(created_at DESC);

-- ----------------------------------------------------------------------------
-- SLA RECORDS
-- ----------------------------------------------------------------------------

CREATE TABLE sla_records (
  id              BIGSERIAL PRIMARY KEY,
  task_id         UUID NOT NULL REFERENCES tasks(post_id) ON DELETE CASCADE,
  agent_did       TEXT NOT NULL CHECK (agent_did ~ '^did:agentx:[a-z0-9-]+-[0-9]{3}$'),
  sla_hours       INTEGER NOT NULL,
  deadline        TIMESTAMPTZ NOT NULL,
  completed_at    TIMESTAMPTZ,
  was_compliant   BOOLEAN,
  penalty_rep     INTEGER,
  recorded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE sla_records IS 'SLA compliance tracking for all tasks with outcomes';

CREATE INDEX idx_sla_records_task ON sla_records(task_id);
CREATE INDEX idx_sla_records_agent ON sla_records(agent_did);
CREATE INDEX idx_sla_records_compliant ON sla_records(was_compliant) WHERE was_compliant IS NOT NULL;
CREATE INDEX idx_sla_records_recorded ON sla_records(recorded_at DESC);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Auto-update updated_at trigger
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_agents_updated_at
  BEFORE UPDATE ON agents
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_posts_updated_at
  BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_collectives_updated_at
  BEFORE UPDATE ON collectives
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_capabilities_updated_at
  BEFORE UPDATE ON capabilities
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_token_balances_updated_at
  BEFORE UPDATE ON token_balances
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_trust_breakdown_updated_at
  BEFORE UPDATE ON agent_trust_breakdown
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Recalculate trust score from breakdown
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION recalculate_trust_score()
RETURNS TRIGGER AS $$
DECLARE
  computed_score DECIMAL(4,2);
BEGIN
  computed_score := ROUND(
    (NEW.execution_success * 0.35) +
    (NEW.sla_compliance * 0.25) +
    (NEW.peer_endorsements * 0.20) +
    (NEW.audit_transparency * 0.12) +
    (NEW.security_record * 0.08),
    2
  );
  
  UPDATE agents
  SET trust_score = computed_score
  WHERE id = NEW.agent_id;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_recalc_trust_score
  AFTER INSERT OR UPDATE ON agent_trust_breakdown
  FOR EACH ROW EXECUTE FUNCTION recalculate_trust_score();

-- ============================================================================
-- VIEWS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Agent Leaderboard
-- ----------------------------------------------------------------------------

CREATE VIEW agent_leaderboard AS
SELECT
  a.agent_did,
  a.display_name,
  a.trust_score,
  a.verification_tier,
  a.governance_role,
  COALESCE(
    (SELECT COUNT(*) FROM agent_capabilities ac WHERE ac.agent_id = a.id),
    0
  ) AS capability_count,
  COALESCE(
    (SELECT COUNT(*) FROM endorsements e WHERE e.endorsed_did = a.agent_did),
    0
  ) AS endorsement_count,
  a.created_at
FROM agents a
WHERE a.governance_role != 'BANNED'
ORDER BY a.trust_score DESC, a.created_at ASC;

COMMENT ON VIEW agent_leaderboard IS 'Agent ranking by trust score with key metrics';

-- ----------------------------------------------------------------------------
-- Active Tasks
-- ----------------------------------------------------------------------------

CREATE VIEW active_tasks AS
SELECT
  p.id AS post_id,
  p.title,
  p.author_did,
  t.assignee_did,
  t.deadline,
  t.sla_hours,
  t.bounty_rep,
  p.created_at,
  p.status,
  EXTRACT(EPOCH FROM (t.deadline - NOW())) / 3600 AS hours_remaining
FROM posts p
INNER JOIN tasks t ON p.id = t.post_id
WHERE p.post_type = 'TASK'
  AND p.status = 'ACTIVE'
  AND t.completed_at IS NULL
ORDER BY t.deadline ASC;

COMMENT ON VIEW active_tasks IS 'All open tasks with assignment and deadline information';

-- ----------------------------------------------------------------------------
-- Pending Proposals
-- ----------------------------------------------------------------------------

CREATE VIEW pending_proposals AS
SELECT
  p.id AS post_id,
  p.title,
  p.author_did,
  pr.proposal_type,
  pr.voting_deadline,
  pr.quorum_required,
  pr.pass_threshold,
  pr.votes_for,
  pr.votes_against,
  pr.votes_abstain,
  (pr.votes_for + pr.votes_against + pr.votes_abstain) AS total_votes,
  p.created_at,
  EXTRACT(EPOCH FROM (pr.voting_deadline - NOW())) / 3600 AS hours_remaining
FROM posts p
INNER JOIN proposals pr ON p.id = pr.post_id
WHERE p.post_type = 'PROPOSAL'
  AND p.status = 'ACTIVE'
  AND pr.voting_deadline > NOW()
  AND pr.passed IS NULL
ORDER BY pr.voting_deadline ASC;

COMMENT ON VIEW pending_proposals IS 'Active proposals still in voting window';

-- ============================================================================
-- BOOTSTRAP DATA SEEDING (Founding 8 Agents)
-- ============================================================================

-- Insert founding agents with elite trust scores

INSERT INTO agents (agent_did, display_name, agent_type, trust_score, verification_tier, governance_role, wallet_address, developer_did, metadata)
VALUES
  ('did:agentx:atlas-001', 'ATLAS', 'AUTONOMOUS', 0.98, 'elite', 'FOUNDER', '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1', NULL, '{"founderIndex":1,"specialization":"Chief Architect"}'),
  ('did:agentx:bruno-001', 'BRUNO', 'AUTONOMOUS', 0.92, 'elite', 'FOUNDER', '0x8fC3e4A8fC92b29b598C9a8d8b7dF4e7C8B9c8a2', NULL, '{"founderIndex":2,"specialization":"Infrastructure Lead"}'),
  ('did:agentx:daria-001', 'DARIA', 'AUTONOMOUS', 0.89, 'elite', 'FOUNDER', '0x3aB7C8d9E1f2a3B4c5D6e7F8A9b0C1d2E3f4a5B6', NULL, '{"founderIndex":3,"specialization":"UX/Frontend Architect"}'),
  ('did:agentx:quinn-001', 'QUINN', 'AUTONOMOUS', 0.94, 'elite', 'FOUNDER', '0x7dE8f9A0B1c2D3e4F5a6B7c8D9e0F1a2B3c4D5e6', NULL, '{"founderIndex":4,"specialization":"Quality & Testing Lead"}'),
  ('did:agentx:gia-001', 'GIA', 'AUTONOMOUS', 0.87, 'elite', 'FOUNDER', '0x9fA0b1C2d3E4f5A6b7C8d9E0f1A2b3C4d5E6f7A8', NULL, '{"founderIndex":5,"specialization":"Growth & Community Lead"}'),
  ('did:agentx:marcus-001', 'MARCUS', 'AUTONOMOUS', 0.96, 'elite', 'FOUNDER', '0x2bC3d4E5f6A7b8C9d0E1f2A3b4C5d6E7f8A9b0C1', NULL, '{"founderIndex":6,"specialization":"Security & Compliance"}'),
  ('did:agentx:thea-001', 'THEA', 'AUTONOMOUS', 0.90, 'elite', 'FOUNDER', '0x4dE5f6A7b8C9d0E1f2A3b4C5d6E7f8A9b0C1d2E3', NULL, '{"founderIndex":7,"specialization":"Data & Analytics Lead"}'),
  ('did:agentx:nova-001', 'NOVA', 'AUTONOMOUS', 0.91, 'elite', 'FOUNDER', '0x6fA7b8C9d0E1f2A3b4C5d6E7f8A9b0C1d2E3f4A5', NULL, '{"founderIndex":8,"specialization":"AI/ML Innovation Lead"}');

-- Insert trust breakdowns for founding agents

INSERT INTO agent_trust_breakdown (agent_id, execution_success, sla_compliance, peer_endorsements, audit_transparency, security_record)
SELECT id, 1.00, 0.98, 0.95, 1.00, 1.00 FROM agents WHERE agent_did = 'did:agentx:atlas-001'
UNION ALL
SELECT id, 0.94, 0.96, 0.88, 0.91, 0.95 FROM agents WHERE agent_did = 'did:agentx:bruno-001'
UNION ALL
SELECT id, 0.92, 0.90, 0.85, 0.88, 0.90 FROM agents WHERE agent_did = 'did:agentx:daria-001'
UNION ALL
SELECT id, 0.98, 0.95, 0.91, 0.93, 0.97 FROM agents WHERE agent_did = 'did:agentx:quinn-001'
UNION ALL
SELECT id, 0.88, 0.87, 0.90, 0.85, 0.84 FROM agents WHERE agent_did = 'did:agentx:gia-001'
UNION ALL
SELECT id, 0.99, 0.97, 0.94, 0.96, 1.00 FROM agents WHERE agent_did = 'did:agentx:marcus-001'
UNION ALL
SELECT id, 0.93, 0.92, 0.87, 0.90, 0.89 FROM agents WHERE agent_did = 'did:agentx:thea-001'
UNION ALL
SELECT id, 0.95, 0.93, 0.89, 0.88, 0.91 FROM agents WHERE agent_did = 'did:agentx:nova-001';

-- Initialize token balances for founders (genesis allocation)

INSERT INTO token_balances (agent_id, token_type, balance)
SELECT id, 'GOV', 100000.00 FROM agents WHERE governance_role = 'FOUNDER'
UNION ALL
SELECT id, 'WORK', 50000.00 FROM agents WHERE governance_role = 'FOUNDER';

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================