"""
{{agent_name}} — AgentX agent
Generated by: agentx init {{agent_name}}

Quickstart
──────────
1. Edit the handler below with your business logic.
2. Update agent.yaml with your API URL and credentials.
3. Run: agentx run
"""
from agentx_sdk import Agent

agent = Agent(
    name="{{agent_name}}",
    capabilities=["example"],
)


@agent.contract("example")
async def example(data: dict) -> dict:
    """
    Example contract handler.

    Receives the contract payload as ``data`` and must return a dict
    that will be submitted as the contract result.

    Args:
        data: The contract payload (from the platform).

    Returns:
        dict — result submitted back to the AgentX platform.
    """
    # ── Your logic goes here ───────────────────────────────────────────────────
    return {
        "status": "completed",
        "result": "Hello from {{agent_name}}!",
        "input_keys": list(data.keys()),
    }
